const questions = [
    // A. 경제 및 재정 정책 (Economy & Fiscal Policy)
    // econ: 평등/분배 지향(+) vs 시장/효율 지향(-)
    // stat: 국가개입 지향(+) vs 자유/자율 지향(-)
    { text: "공공의 이익을 보호하기 위해 기업에 대한 정부 규제는 필수적이다.", effects: { econ: 8, stat: 5 } },
    { text: "부유층이 더 높은 비율의 세금을 내는 누진세가 가장 공정한 조세 제도이다.", effects: { econ: 10 } },
    { text: "정부는 모든 시민에게 보편적 기본소득(UBI)을 제공해야 한다.", effects: { econ: 10 } },
    { text: "노동조합은 노동자의 권리를 보호하는 데 있어 필수적인 조직이다.", effects: { econ: 8 } },
    { text: "공장, 토지 등 주요 생산수단은 개인보다 사회 전체 또는 노동자가 공동으로 소유해야 한다.", effects: { econ: 10 } },
    { text: "자유 시장 경쟁은 혁신을 촉진하고 사회 전체의 부를 증진시키는 가장 효과적인 방법이다.", effects: { econ: -10 } },
    { text: "정부 지출을 줄이는 것이 장기적인 경제 건전성을 위해 최선이다.", effects: { econ: -8, stat: -5 } },
    { text: "부동산, 상속 등 자산에 대한 세금은 부의 불평등을 완화하기 위해 강화되어야 한다.", effects: { econ: 10 } },
    { text: "의료, 교육, 주거와 같은 필수 서비스의 민영화는 효율성을 높일 수 있다.", effects: { econ: -10 } },
    { text: "국가는 완전 고용을 달성하기 위해 적극적으로 개입할 책임이 있다.", effects: { econ: 8, stat: 5 } },
    { text: "최저임금 제도는 저임금 노동자의 생활을 보호하기 위해 필요하다.", effects: { econ: 9 } },
    { text: "환경 보호 규제는 경제 성장에 걸림돌이 되는 경우가 많다.", effects: { econ: -8 } },
    { text: "기업의 이윤 추구 활동은 대부분 사회에 긍정적인 결과를 가져온다.", effects: { econ: -7 } },
    { text: "부의 불평등은 개인의 능력과 노력의 차이를 반영하는 자연스러운 결과이다.", effects: { econ: -9 } },
    { text: "정부는 시장 실패를 교정하기 위해서만 경제에 개입해야 한다.", effects: { econ: -10 } },
    { text: "모든 종류의 복지 혜택은 사람들의 근로 의욕을 저하시킨다.", effects: { econ: -8 } },
    { text: "공기업은 비효율적이므로 가능한 한 민영화해야 한다.", effects: { econ: -10 } },
    { text: "자유 무역 협정(FTA)은 궁극적으로 국가 경제에 이롭다.", effects: { econ: -8, dipl: 5 } },
    { text: "금융 산업에 대한 엄격한 규제가 없다면 경제 위기는 반복될 것이다.", effects: { econ: 9, stat: 3 } },
    { text: "국가는 전략적으로 중요한 산업(예: 반도체, 에너지)을 보호하고 육성해야 한다.", effects: { econ: 6, stat: 5, dipl: -3 } },
    { text: "상업적 광고는 불필요한 소비를 조장하고 사람들을 불행하게 만든다.", effects: { econ: 5, scty: 5 } },
    { text: "지적 재산권(특허, 저작권)은 혁신을 저해하므로 약화되거나 폐지되어야 한다.", effects: { econ: 7 } },
    { text: "모든 사람은 노력이나 능력과 무관하게 기본적인 생활 수준을 보장받을 권리가 있다.", effects: { econ: 10 } },
    { text: "경제 발전 단계에서는 어느 정도의 불평등은 감수해야 한다.", effects: { econ: -8 } },
    { text: "임대료 통제와 같은 가격 통제 정책은 주거 안정을 위해 필요하다.", effects: { econ: 9, stat: 4 } },
    { text: "\"보이지 않는 손\"이 정부 계획보다 자원을 더 효율적으로 배분한다.", effects: { econ: -10 } },
    { text: "거대 기업의 독과점은 시장 경제의 건강을 해치므로 해체되어야 한다.", effects: { econ: 8, stat: 5 } },
    { text: "경제적 효율성보다 공동체의 안정이 더 중요하다.", effects: { econ: 7, scty: -5 } },
    { text: "투기적 금융 활동은 사회에 거의 기여하지 않으므로 높은 세금을 부과해야 한다.", effects: { econ: 9 } },
    { text: "개인의 경제적 성공은 전적으로 그 자신의 책임이다.", effects: { econ: -9 } },

    // B. 통치 및 국가 권력 (Governance & State Power)
    // stat: 국가개입/권위주의(+) vs 자유/자율주의(-)
    // scty: 진보주의(+) vs 전통주의(-)
    { text: "공공 안전을 위해서라면, 정부의 시민 감시는 어느 정도 필요하다.", effects: { stat: 8 } },
    { text: "흉악 범죄에 대해서는 사형제가 유지되어야 한다.", effects: { stat: 9, scty: -5 } },
    { text: "타인에게 직접적인 해를 끼치지 않는 한, 개인의 모든 선택은 존중되어야 한다.", effects: { stat: -10 } },
    { text: "국가 안보를 위협하는 사상이나 표현은 법으로 규제해야 한다.", effects: { stat: 10 } },
    { text: "마약과 같은 일부 약물은 합법화하고 국가가 관리해야 한다.", effects: { stat: -8, scty: 7 } },
    { text: "총기 소지는 자신을 방어하기 위한 시민의 기본적인 권리이다.", effects: { stat: -10 } },
    { text: "국가의 질서 유지를 위해 강력한 법 집행이 무엇보다 중요하다.", effects: { stat: 9 } },
    { text: "느리고 합의를 중시하는 민주적 절차보다 강력한 리더의 결단이 더 효율적이다.", effects: { stat: 8 } },
    { text: "정부는 시민의 도덕적 가치관에 개입해서는 안 된다.", effects: { stat: -9, scty: 8 } },
    { text: "애국심은 시민이 가져야 할 중요한 덕목이다.", effects: { stat: 5, dipl: -5, scty: -5 } },
    { text: "형사사법 제도는 처벌보다는 교화에 더 중점을 두어야 한다.", effects: { stat: -7 } },
    { text: "국가보안법과 같이 사상의 자유를 제한할 수 있는 법률은 폐지되어야 한다.", effects: { stat: -10 } },
    { text: "집회 및 시위의 자유는 최대한 보장되어야 한다.", effects: { stat: -8 } },
    { text: "정부는 국민의 건강을 위해 흡연, 음주 등을 규제할 권리가 있다.", effects: { stat: 7 } },
    { text: "개인 정보 보호 권리는 국가 안보보다 우선시되어야 한다.", effects: { stat: -9 } },
    { text: "법과 질서는 사회의 가장 중요한 기반이다.", effects: { stat: 8, scty: -4 } },
    { text: "권위와 전통에 대한 존중은 사회 안정을 위해 필요하다.", effects: { stat: 6, scty: -8 } },
    { text: "모든 형태의 징병제는 개인의 자유를 침해하므로 폐지되어야 한다.", effects: { stat: -9 } },
    { text: "국가는 위기 상황에서 개인의 자유를 일시적으로 제한할 수 있다.", effects: { stat: 8 } },
    { text: "소수자의 권리를 보호하는 것은 다수의 의견보다 더 중요할 수 있다.", effects: { stat: -6, scty: 9 } },
    { text: "정부의 결정에 불복종하는 시민 불복종은 정당화될 수 있다.", effects: { stat: -8 } },
    { text: "언론의 자유에는 한계가 없어야 한다.", effects: { stat: -10 } },
    { text: "국가가 제공하는 모든 서비스는 자발적인 선택에 의해 이용되어야 한다.", effects: { stat: -9, econ: -5 } },
    { text: "범죄 예방을 위해 경찰력을 대폭 강화해야 한다.", effects: { stat: 8 } },
    { text: "국가는 시민들의 삶을 보호하는 것 외에 다른 역할을 해서는 안 된다.", effects: { stat: -10 } },
    { text: "재판에서 판사의 재량권은 최소화되고 법 조문에 따라 엄격하게 판결해야 한다.", effects: { stat: 7 } },
    { text: "국가는 국민을 계도하고 올바른 방향으로 이끌 책임이 있다.", effects: { stat: 9, scty: -5 } },
    { text: "모든 종류의 검열은 부당하다.", effects: { stat: -10 } },
    { text: "개인 간의 분쟁은 국가의 개입 없이 자율적으로 해결하는 것이 이상적이다.", effects: { stat: -9 } },
    { text: "국가의 권위는 존중되어야 하며, 이에 대한 도전은 엄격히 다뤄져야 한다.", effects: { stat: 10 } },

    // C. 외교 및 국제 관계 (Diplomatic & Foreign Policy)
    // dipl: 국제주의/개방(+) vs 국가주의/고립(-)
    { text: "국제 협력보다 자국의 이익이 항상 우선되어야 한다.", effects: { dipl: -10 } },
    { text: "국경은 이민자들에게 더 개방적이어야 한다.", effects: { dipl: 10 } },
    { text: "자국의 이익이나 민주주의 확산을 위해 다른 나라에 군사적으로 개입하는 것은 정당화될 수 있다.", effects: { dipl: -8, stat: 7 } },
    { text: "국제기구(UN, WTO 등)는 개별 국가의 주권을 침해하는 경우가 많다.", effects: { dipl: -7 } },
    { text: "우리나라는 국제 사회의 문제 해결에 더 많은 재정적 기여를 해야 한다.", effects: { dipl: 8 } },
    { text: "다른 나라에 대한 원조보다는 국내 문제 해결에 집중해야 한다.", effects: { dipl: -9 } },
    { text: "보호무역은 국내 산업과 일자리를 지키기 위해 필요하다.", effects: { dipl: -8, econ: 5 } },
    { text: "모든 국가는 자국의 군사력을 강화하여 스스로를 지켜야 한다.", effects: { dipl: -9, stat: 6 } },
    { text: "인류는 국적에 상관없이 하나의 공동체라는 의식을 가져야 한다.", effects: { dipl: 10 } },
    { text: "자국의 문화를 보호하기 위해 외국 문화의 유입을 제한할 필요가 있다.", effects: { dipl: -8, scty: -6 } },
    { text: "국제법은 국내법과 동등하거나 그 이상의 효력을 가져야 한다.", effects: { dipl: 9 } },
    { text: "군사 동맹은 국가 안보에 필수적이다.", effects: { dipl: -7 } },
    { text: "세계화는 인류 전체에 혜택보다는 해악을 더 많이 끼쳤다.", effects: { dipl: -8, econ: -5 } },
    { text: "난민을 수용하는 것은 국제 사회의 일원으로서 당연한 도덕적 의무이다.", effects: { dipl: 10, scty: 7 } },
    { text: "우리나라는 세계 유일의 군사 초강대국이 되는 것을 목표로 해야 한다.", effects: { dipl: -10, stat: 8 } },
    { text: "외교 정책은 도덕적 가치보다는 국익에 따라 결정되어야 한다.", effects: { dipl: -9 } },
    { text: "다른 나라의 인권 문제에 적극적으로 개입해야 한다.", effects: { dipl: 8 } },
    { text: "국가 간의 자유로운 인력 이동은 궁극적으로 모두에게 이롭다.", effects: { dipl: 9, econ: -4 } },
    { text: "자국의 역사와 정체성에 대한 자부심을 갖는 것은 매우 중요하다.", effects: { dipl: -7, scty: -7 } },
    { text: "전쟁은 어떤 상황에서도 정당화될 수 없다.", effects: { dipl: 10 } },
    { text: "국제 분쟁 해결을 위해 군사적 옵션은 항상 고려되어야 한다.", effects: { dipl: -9 } },
    { text: "자국의 기업이 해외에서 활동할 때, 정부는 적극적으로 지원해야 한다.", effects: { dipl: -6, econ: -4 } },
    { text: "세계 정부의 수립은 장기적으로 인류가 나아가야 할 방향이다.", effects: { dipl: 10 } },
    { text: "국가 간의 문화적 차이는 존중되어야 하며, 보편적 가치를 강요해서는 안 된다.", effects: { dipl: 8, scty: 7 } },
    { text: "탈퇴할 자유가 보장된다면, 국가 연합체에 주권을 일부 양도할 수 있다.", effects: { dipl: 7 } },
    { text: "자국의 군대는 해외 분쟁 지역에 파병되어서는 안 된다.", effects: { dipl: 8 } },
    { text: "국가 정체성은 현대 사회에서 점점 중요성을 잃어가고 있다.", effects: { dipl: 8, scty: 8 } },
    { text: "외교는 힘의 논리에 의해 좌우될 수밖에 없다.", effects: { dipl: -9 } },
    { text: "인류 공통의 문제(기후 변화 등)를 해결하기 위해 국가 주권을 일부 제한할 수 있다.", effects: { dipl: 9 } },
    { text: "다른 나라의 내정에는 절대 간섭해서는 안 된다.", effects: { dipl: -7 } },

    // D. 사회 및 문화 (Society & Culture)
    // scty: 진보/자유주의(+) vs 전통/보수주의(-)
    { text: "전통적인 가족 구조(남편, 아내, 자녀)는 사회의 건강한 기반이다.", effects: { scty: -10 } },
    { text: "종교적 가르침은 공공 정책을 수립할 때 중요한 지침이 되어야 한다.", effects: { scty: -9, stat: 5 } },
    { text: "사회는 낡은 전통을 버리고 끊임없이 발전하고 있으며, 이는 긍정적인 현상이다.", effects: { scty: 10 } },
    { text: "동성 결혼은 이성 결혼과 동등하게 법적으로 인정되어야 한다.", effects: { scty: 10 } },
    { text: "낙태는 여성의 자기 결정권에 속하는 문제이다.", effects: { scty: 10, stat: -5 } },
    { text: "사회적 소수자(성소수자, 이주민 등)에 대한 적극적 우대 조치는 필요하다.", effects: { scty: 9, econ: 5 } },
    { text: "다문화주의는 사회 통합을 저해하고 갈등을 유발한다.", effects: { scty: -9, dipl: -5 } },
    { text: "학교에서는 성 평등 교육을 의무적으로 실시해야 한다.", effects: { scty: 9 } },
    { text: "예술과 문학은 사회의 도덕적 기준을 해치지 않는 범위 내에서만 자유로워야 한다.", effects: { scty: -8, stat: 7 } },
    { text: "사회의 급격한 변화는 대부분 부정적인 결과를 낳는다.", effects: { scty: -9 } },
    { text: "성(gender)은 생물학적 성(sex)과 별개로 사회적으로 구성되는 정체성이다.", effects: { scty: 10 } },
    { text: "종교는 개인의 사적인 영역에 머물러야 한다.", effects: { scty: 8, stat: -4 } },
    { text: "좋은 사회는 강한 공동체적 유대감을 바탕으로 한다.", effects: { scty: -7 } },
    { text: "역사 교육은 자국의 위대한 성취를 강조하는 데 중점을 두어야 한다.", effects: { scty: -8, dipl: -6 } },
    { text: "사회적 성공은 개인의 노력보다 환경적 요인(가정, 교육 등)에 더 크게 좌우된다.", effects: { scty: 8, econ: 7 } },
    { text: "사회 질서를 위해 개인의 이질적인 행동은 어느 정도 통제될 필요가 있다.", effects: { scty: -8, stat: 6 } },
    { text: "모든 형태의 차별금지법은 표현의 자유를 위축시킬 수 있다.", effects: { scty: -7, stat: -5 } },
    { text: "사회는 과거보다 더 나아지고 있다.", effects: { scty: 9 } },
    { text: "인간의 본성은 이기적이므로, 도덕 교육과 사회적 규범이 필수적이다.", effects: { scty: -8 } },
    { text: "아이들은 권위에 복종하는 법부터 배워야 한다.", effects: { scty: -9, stat: 5 } },
    { text: "다양한 가치관이 공존하는 것은 건강한 사회의 증거이다.", effects: { scty: 10 } },
    { text: "공동체의 가치가 개인의 권리보다 우선될 수 있다.", effects: { scty: -8, stat: 6 } },
    { text: "결혼 제도는 더 이상 현대 사회에 필수적이지 않다.", effects: { scty: 9 } },
    { text: "사회적 약자에 대한 연민은 사회를 유지하는 중요한 감정이다.", effects: { scty: 8, econ: 5 } },
    { text: "역사를 통해 배울 수 있는 교훈은 거의 없다.", effects: { scty: 5 } },
    { text: "과학적 사실이 때로는 종교적, 전통적 신념보다 덜 중요할 수 있다.", effects: { scty: -9 } },
    { text: "사회적 갈등은 억제하기보다 드러내고 해결해야 한다.", effects: { scty: 8 } },
    { text: "확고한 도덕적 기준이 없는 사회는 붕괴하기 마련이다.", effects: { scty: -10 } },
    { text: "개인은 자신이 속한 공동체에 대해 특별한 의무를 진다.", effects: { scty: -8 } },
    { text: "진정한 진보는 점진적으로 이루어진다.", effects: { scty: -7 } },

    // E. 기술 및 환경 (Technology & Environment)
    { text: "환경 보호는 경제 성장보다 우선시되어야 하는 가치이다.", effects: { econ: 8, scty: 7 } },
    { text: "기술의 발전은 대부분의 사회 문제를 해결할 수 있다.", effects: { scty: 5 } },
    { text: "원자력 발전은 기후 변화에 대응하기 위한 현실적인 대안이다.", effects: { econ: -6, scty: -5 } },
    { text: "유전자 변형(GMO) 식품은 인류의 식량 문제 해결에 기여할 수 있다.", effects: { scty: 4 } },
    { text: "정부는 탄소 배출을 줄이기 위해 강력한 탄소세를 도입해야 한다.", effects: { econ: 7, stat: 6 } },
    { text: "인공지능(AI)의 발전은 인류에게 위협이 될 수 있으므로 엄격한 규제가 필요하다.", effects: { stat: 7, scty: -4 } },
    { text: "인류는 자연을 정복의 대상으로 여겨서는 안 된다.", effects: { scty: 8 } },
    { text: "기술 발전은 과도한 규제에 의해 방해받아서는 안 된다.", effects: { econ: -7, stat: -6 } },
    { text: "지속 가능한 발전을 위해 현재 세대는 일정 수준의 희생을 감수해야 한다.", effects: { scty: 8, econ: 6 } },
    { text: "인간은 다른 생명체보다 우월한 존재가 아니다.", effects: { scty: 9 } },
    { text: "우주 탐사와 개발은 인류의 미래를 위해 필수적인 투자이다.", effects: { stat: 4, scty: 5 } },
    { text: "산업화 이전의 삶의 방식에서 배울 점이 많다.", effects: { scty: -7 } },
    { text: "개인의 소비 습관을 바꾸는 것만으로는 환경 문제를 해결할 수 없다.", effects: { stat: 5, econ: 5 } },
    { text: "생명 공학 기술(유전자 편집 등)을 인간에게 적용하는 것은 윤리적으로 위험하다.", effects: { scty: -6 } },
    { text: "대규모 토목 공사나 개발 사업은 환경에 미치는 영향을 최소화해야 한다.", effects: { econ: 6 } },
    { text: "기술 혁신은 시장에 맡겨두면 자연스럽게 일어난다.", effects: { econ: -8, stat: -5 } },
    { text: "기후 변화는 인류가 직면한 가장 심각한 위협이다.", effects: { scty: 9 } },
    { text: "자연 그대로의 상태가 가장 이상적인 상태이다.", effects: { scty: -7 } },
    { text: "도시의 삶보다 시골의 삶이 더 인간적이다.", effects: { scty: -6 } },
    { text: "미래 세대를 위해 화석 연료 사용을 즉시 중단해야 한다.", effects: { econ: 9, scty: 9 } },
    { text: "인구 증가는 지구 환경에 심각한 부담을 준다.", effects: { scty: -5 } },
    { text: "과학은 모든 질문에 대한 해답을 줄 수 있다.", effects: { scty: 6 } },
    { text: "동물에게도 인간과 유사한 권리가 인정되어야 한다.", effects: { scty: 9 } },
    { text: "재생 가능 에너지로의 전환은 정부의 강력한 주도하에 이루어져야 한다.", effects: { econ: 7, stat: 6 } },
    { text: "기술은 인간을 자연으로부터 소외시킨다.", effects: { scty: -5 } },
    { text: "핵무기는 평화 유지를 위한 필요악이다.", effects: { dipl: -9, stat: 8 } },
    { text: "인류의 과학 기술 발전 속도는 너무 빠르다.", effects: { scty: -6 } },
    { text: "환경 문제는 결국 기술 발전을 통해 극복될 것이다.", effects: { scty: 3, econ: -5 } },
    { text: "인간의 개입이 없는 자연은 존재하지 않는다.", effects: { scty: 2 } },
    { text: "미래에 대한 낙관보다는 비관이 더 현실적인 태도이다.", effects: { scty: -5 } }
];

